env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - 'airbnb'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  {
    'react/jsx-filename-extension': [1, { 'extensions': ['.js', '.jsx', '.ts', '.tsx'] }],
    'react/jsx-one-expression-per-line': [0],
    'no-use-before-define': ['off'],
    'import/no-unresolved': 'off',
    'import/extensions': 'off',
    'comma-dangle': 'off',
    'object-curly-newline': 'off',
    'arrow-body-style': [0],
    'react/jsx-props-no-spreading': 'off',
    'no-shadow': 'off',
    'no-unused-vars': 'off',
    '@typescript-eslint/no-unused-vars': 'error',
    'operator-linebreak': 'off',
    'react/prop-types': 'off',
    'react/require-default-props': 'off',
    'jsx-a11y/label-has-associated-control': 'off',
    'implicit-arrow-linebreak': 'off',
    'function-paren-newline': 'off',
    'indent': 'off',
    'no-debugger': 'off',
    'jsx-a11y/control-has-associated-label': 'off',
    'react/jsx-closing-bracket-location': 'off',
    'jsx-a11y/anchor-is-valid': 'off'
  }
