env:
  browser: false
  es2020: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  {
    'import/extensions':
      [
        'error',
        'ignorePackages',
        { 'js': 'never', 'jsx': 'never', 'ts': 'never', 'tsx': 'never' }
      ],
    'no-useless-constructor': 'off',
    'import/prefer-default-export': 'off',
    'no-unused-vars': 'off',
    'no-empty-function': 'off',
    'object-curly-newline': 'off',
    'no-undef': 'off',
    'arrow-parens': 'off',
    'import/no-unresolved': 'off',
    'comma-dangle': 'off',
    'implicit-arrow-linebreak': 'off',
    '@typescript-eslint/no-useless-constructor': ['error'],
    'no-shadow': 'off',
    '@typescript-eslint/no-shadow': 'error',
    'function-paren-newline': 'off',
    'class-methods-use-this': 'off'
  }
settings:
  'import/resolver':
    'node':
      'extensions': ['.js', '.jsx', '.ts', '.tsx']
